### ISSUE TITLE
Display waveform along with the tracks

### ISSUE THREAD

**Issue by emoon** [emoon/rocket#114]
It would be great to load wavefile and display it along with the track. Perhaps switchable between regular wave/FFT?

cc @pixelmager

**Comment by emoon** [comment]
So I have FFT data decode working (I think :) and wave data. I just wonder if you @yupferris or @pixelmager has any idea of how I should display the data? I use this function http://www.un4seen.com/doc/#bass/BASS_ChannelGetData.html and I get back some FFT data.

Also right now I just merge stereo -> mono as intended to display it as one "waveform" Other suggestions?

**Comment by yupferris** [comment]
mono should be fine; I wouldn't worry too much about that at least (although you might want to worry about how you mix to mono, but as long as you're not averaging you're probably fine).

As for rendering, I'm not too sure myself. I really dig tooll.io's fft view (for lack of a better screenshot: https://camo.githubusercontent.com/ae07aa75c6a2e33888d53ce2c15e1077be31b35b/687474703a2f2f692e696d6775722e636f6d2f653169647453522e676966) but I'm not 100% sure how to render it. Typically you end up taking the visible window of "samples" (bins in your case) and do some kind of average over time and space which is basically just CPU scaling but a bit smarter than just bilinear and dump that to the gpu. It usually ends up being a lot more performant than it sounds :)

**Comment by yupferris** [comment]
seeing as your zoom doesn't change though, you can probably get away with doing the fft and scaling offline, and just blit out the visible portions of it when you need to redraw.

**Comment by emoon** [comment]
Yeah that is my plan. When user selects the tune my plan is to spawn another thread and pre-process all the data that is needed and then just blit sections of the data to a texture.

**Comment by yupferris** [comment]
ofc that will take a bunch of memory, but you could do it in "slabs" and keep a thread churning to make sure relevant ones are ready, and the others can be evicted

**Comment by yupferris** [comment]
another thing: you'll have to know the row/time ratio in the tool to calculate the scaling; does this editor already have that knowledge? iirc the original doesn't; that was up to the client

**Comment by yupferris** [comment]
also the scaling should be non-linear in the frequency domain :)

**Comment by emoon** [comment]
Well.. say that you have 10000 rows and that each row is 8 pixels (or something, might be a bit more) and each line of wave form is 128 bytes. That will become 10000*8*128/(1024*1024) = ~10 meg of data so I don't think that is such a big issue.

**Comment by yupferris** [comment]
totally, I forgot about the temporal scaling when I mentioned that and was doing the math memory size in my head based on a 20mb estimate for the original short data :D

**Comment by emoon** [comment]
It's very true though that I don't know bpm and such. It's always the client that say the current row the demo is on... hum

**Comment by yupferris** [comment]
[ground control](https://github.com/edoreshef/ground-control) is doing it somehow; likely with just entering it in the tool, but I don't see it in the screenshot anywhere at least. That wouldn't cover cases where the consumer is using a different formula or has like half/double time, though.

**Comment by alkama** [comment]
ground control indeed has "bpm" and "rows per beat" as a project settings.

**Comment by yupferris** [comment]
But these are the kind of caveats I'd be happy to live with I'd imagine :)

**Comment by yupferris** [comment]
bpm and rows per beat would make a lot of sense I think

**Comment by emoon** [comment]
Yeah then it's easy to figure it out.. otherwise it would be hard.

**Comment by yupferris** [comment]
I'd say go with that then and just document in the readme what the client formula should be

**Comment by emoon** [comment]
Will do!

**Comment by emoon** [comment]
So I guess rows per beat setting can actually be (or should?) as this one https://github.com/emoon/rocket/issues/45

**Comment by emoon** [comment]
tooll.io is open source so it should be possible to figure out how it's being done.

**Comment by emoon** [comment]
Also do you think there is any benefit of having Wave data as well or is only FFT useful?

**Comment by emoon** [comment]
This is funny :) https://github.com/framefield/tooll/blob/master/Tooll/Components/Helper/GenerateSoundImage.cs here is the code.. They use BASS also so will be very easy to use :)

**Comment by yupferris** [comment]
they're both useful, I'd just argue fft is _more_ useful. I doubt I'd ever want to see both, but your original toggle idea could be nice.

**Comment by emoon** [comment]
Yeah will do.

**Comment by pixelmager** [comment]
I'm with ferris, fft all the way
(I have fft running in my demo-window, but a lot better to have it in rocket).

**Comment by emoon** [comment]
Cool. In progress now :)

**Comment by emoon** [comment]
![rocktet_fft](https://cloud.githubusercontent.com/assets/350822/18806967/41f9d5a2-823c-11e6-9cb9-20b96cbcd871.png)

WIP :)

**Comment by emoon** [comment]
Mac version is ready for a spin for anyone who wants to try it out :) https://dl.dropboxusercontent.com/u/5205843/RocketEditor1.2beta.zip feedback is most welcome.

**Comment by yupferris** [comment]
looks like the build is sierra-only; that won't do :)

**Comment by emoon** [comment]
What?! You are not running the latest OS yet? :) But yeah, that shouldn't be required. I wonder what would cause that...

**Comment by emoon** [comment]
Updated. Try if it works now (untested on earlier OS version)

**Comment by yupferris** [comment]
did a quick test here; works great! Liked the little loading indicator too, hehe. Will give it a more proper go this evening :)

**Comment by yupferris** [comment]
actually i'm having a lot of problems with how it scrolls. It appears to follow the tracker normally as long as the waveform doesn't take up the whole screen, but then as soon as I scroll far enough for the wave form to start at the top of the screen, it looks like it only scrolls 1 pixel per row or so, regardless of the rows/beat value. Sounds confusing, but looks like this:

![big gif incoming](https://cloud.githubusercontent.com/assets/3166056/19005114/2964a432-8759-11e6-8265-ce36bb4d09c6.gif)

Also with this particular song I had to use 64 rows/beat, but that may actually be correct; just seems high.

**Comment by emoon** [comment]
So 64 rows/beat seems quite high. The way the "row rate" is calculated (which is also included in the bass example) is `(bpm / 60.0) * rows per beat` which means than when doing a playback of this track and say that it's 1 min long would mean `(((175.0 / 60.0) * 64.0) * 60.0) = 11200` rows. So if you do a playback of the demo will you after 1 min be on row 11200 ? That sounds quite a lot.

Here is the example code for BASS https://github.com/emoon/rocket/blob/master/example_bass/example_bass.cpp#L23

I think I have a fix for the code but I want to make sure this is accurate first.

**Comment by yupferris** [comment]
It looks like I've got that right actually:

```
        // TODO: Don't hardcode bpm
        let bpm = 175.0;
        let row_rate = bpm / 60.0 * 8.0;
        let row = time * row_rate;
```

**Comment by yupferris** [comment]
given `rows per beat` is 8, which it is in the BASS example

**Comment by yupferris** [comment]
So 64 for `rows/beat` in the editor can make sense if there's also another straggling `8` in that calc somewhere; it should probably match the rows/beat in the demo's timing code (which should be 8 in this case I think)

**Comment by yupferris** [comment]
Which I expected I might find here, but nope: https://github.com/emoon/rocket/blob/fft-view/ogl_editor/src/RenderAudio.c#L74

Strange, I'm not exactly sure why this is messed up

**Comment by yupferris** [comment]
Unless perhaps `rowSpacing` is 8.. perhaps it's this 8? :) https://github.com/emoon/rocket/blob/fft-view/ogl_editor/src/Editor.c#L556

**Comment by yupferris** [comment]
ah, I think it might be `font_size` here (which is 8): https://github.com/emoon/rocket/blob/fft-view/ogl_editor/src/TrackView.c#L779

perhaps the rendering is not taking that into account properly

Sorry for the spam btw; done digging now :)

**Comment by emoon** [comment]
I have updated the code.. but the the calculating you do in run-time needs to match what you set in the editor (otherwise a row will not match to the correct position that is being displayed for the fft data)

**Comment by emoon** [comment]
Or would it make sense to have this as two separate values? (ie one is only for the stepping in the editor and the other is for calculating the `rows per sec` value)

**Comment by yupferris** [comment]
ok just tested the updated executable; this worked perfectly without any changes to my code. I'm guessing the "weird" scrolling I had before was just a mismatch between the rows/beat ratio in the client and in the editor (which again was because the scaling was incorrect). So, this fixes the issue I had, no problem :)

As for the second comment, to have as two values, I don't really see much usefulness there.

**Comment by emoon** [comment]
Alright. Cool :)

**Comment by emoon** [comment]
Will close this one for now as FFT support is in. If there is need for a seeing the waveform instead there can be a new issue created for it.
