### ISSUE TITLE
Customize readme

### ISSUE THREAD

**Issue by yupferris** [emoon/rocket#115]
Certain sections of the readme probably don't apply to this fork so much, for example: https://github.com/emoon/rocket#bugs-and-feedback

> Please report bugs or other feedback to the GNU Rocket mailing list: gnu-rocket@googlegroups.com

probably don't want to send people to the original mailing list if they have problems with this fork :)

**Comment by emoon** [comment]
Doh! will fix :)

**Comment by emoon** [comment]
Well the real readme is here actually https://github.com/emoon/rocket/tree/master/ogl_editor

**Comment by yupferris** [comment]
ah ofc, somehow I forgot about that one :) Perhaps link it in the forked readme as well?

**Comment by emoon** [comment]
Yeah will do.

**Comment by emoon** [comment]
Fixed (will be merged to master when fft-view is done)
