### ISSUE TITLE
Highlights on tracks should use rows/beat

### ISSUE THREAD

**Issue by yupferris** [emoon/rocket#117]
If I set the rows/beat to something that's not a power of 2, for example 12 (which is useful in the current track we're working with as it uses both 16th and 8th triplet notes), the row number column will use this to highlight rows that are multiples of this number, but the highlighted ticks in the individual tracks appear to always highlight the 8th row. Example shown below:

![screen shot 2016-10-06 at 7 19 33 pm](https://cloud.githubusercontent.com/assets/3166056/19162894/0205ba84-8bfa-11e6-863b-cddf7000e81e.png)

**Comment by yupferris** [comment]
This might have been better filed as part of #45; sorry about that!

**Comment by emoon** [comment]
Ah :) Will fix!

**Comment by emoon** [comment]
Fixed! Zip is updated.
