### ISSUE TITLE
Add travis and appveyor

### ISSUE THREAD

**Issue by emoon** [emoon/rocket#119]
Would be great to have and also make it much easier to auto-deploy new version.

**Comment by alkama** [comment]
Since CMake is in place and it's been done for https://github.com/Gargaj/Bonzomatic it should be easy to set it all up for all targets

**Comment by emoon** [comment]
I have set it up several times before so should be easy :)

**Comment by alkama** [comment]
Now we have a super easy boulevard for appveyor and travis-ci!

**Comment by emoon** [comment]
Github Actions has now been set up
