### ISSUE TITLE
Editor crashes on OSX occasionally when client [re]connects

### ISSUE THREAD

**Issue by yupferris** [emoon/rocket#122]
I don't have a trace atm, but I'll post when I get one. Generally happens if the client has to reconnect a few times.

**Comment by emoon** [comment]
And you said this seems to work better on Windows right?

**Comment by yupferris** [comment]
that's correct; I don't think I ever saw this happen on Windows.

**Comment by alkama** [comment]
I've seen that too, but hard to track because it aint super recurrent.
I'll try to keep a crashlog next time!
Good to see you both pushing the tool forward \o/
I promise I'll return with some fixes too. Been distracted toying with path tracing, the non realtime kind :)

**Comment by emoon** [comment]
I will likely try to set up some stress test for this in order if i can get the crash to happen but yes, if you see it please keep the crash dump/log around :)

**Comment by emoon** [comment]
Closing this one until we have a better repo of it
