### ISSUE TITLE
Make the project the root of the repo, submodule original rocket

### ISSUE THREAD

**Issue by alkama** [emoon/rocket#126]
I had this idea, possibly bad, that it might be easier and cleaner not to be a direct fork of the original rocket anymore (since we dont share much from it) but to submodule it instead.

It would:
- bring more visibility to the real ReadMe and release of this project.
- remove the need to cherry pick or rebase evolutions done on their side, just point the submodule to the right commit.
- ease having travis and appveyor build and find their settings on the root.

**Comment by emoon** [comment]
I have thought about the same thing and I agree. :)

**Comment by emoon** [comment]
I wonder if it's possible to do without starting a fully new repo? As this is a fork of the original one.

**Comment by alkama** [comment]
Could contact github support to sever the fork link. It's the only solution that doesnt change the repo itself.
But of course, one could start a fresh one.
Or just keep using that fork, do the changes, and not care about ever merging upstream :)
That last solution is probably breaking spacetime continuum: forking AND submoduling \o/ It's so awfully mind-blowing that it might be fun to try.

**Comment by emoon** [comment]
Yeah I'm thinking that the last one is to ask for trouble for sure :) Think starting a new (and renaming the current one as deprecated or something) might work.

**Comment by alkama** [comment]
Of course.
But you could delete and recreate, it should still be able to keep the same name, and thus, same url :)
If you commit the same git to that, maybe ppl having forked your repo will still be fine, since the SHA will be kept in sync?

About the web links though, looking at how ppl tend to have linked the ogl_editor subfolder directly, those links are doomed to be broken, unless we keep an ogl_editor subfolder just to have a readme to tell to go to root folder.

**Comment by alkama** [comment]
I think the reason ppl try to keep the repo instead of making a new one is usually to keep the wiki and issues, since those are not subject to migration

**Comment by alkama** [comment]
So if not in a extreme hurry, the github support way is probably fine :)

**Comment by emoon** [comment]
Yeah I guess so :)

**Comment by emoon** [comment]
Mailed support about this now :)

**Comment by emoon** [comment]
Move is now completed! (also they moved the forks of this repo with it)

**Comment by alkama** [comment]
awesome \o/

**Comment by alkama** [comment]
Now, question is: want me to take care of the move and submoduling or you're already on it? :)

**Comment by emoon** [comment]
If you want to do it that would be great, I haven't started on it :)
