### ISSUE TITLE
PageDown/PageUp don't work

### ISSUE THREAD

**Issue by seece** [emoon/rocket#131]
I downloaded the latest binary release but seems like I can't scroll using PageUp or PageDown, and I can't delete notes with Delete. Scrolling works for example with Alt+Up though.

I have a Finnish locale but changing the keyboard layout to US didn't affect anything.
I'm running Windows 7 N x64.

**Comment by emoon** [comment]
Hi,

Thanks for the report. I will look into to the issues. Is backspace working for deleting keys?

**Comment by seece** [comment]
Thanks for the quick reply. Yes backspace works.

**Comment by emoon** [comment]
Hi,

I have updated this file https://dl.dropboxusercontent.com/u/5205843/RocketEditor1.2beta-Win.zip with the latest build (I tested locally and Page up/down worked fine in that version)

Currently only backspace is used for deleting and not delete. I hope that will work for you?

**Comment by seece** [comment]
PageDown and PageUp work now, thanks!

2017-04-10 14:28 GMT+03:00 Daniel Collin <notifications@github.com>:

**Comment by emoon** [comment]
Great! np :)
