### ISSUE TITLE
FYI: Python Client

### ISSUE THREAD

**Issue by einarf** [emoon/rocket#134]
I made a python client last night and used this editor for testing.
https://github.com/Contraz/pyrocket (No dependencies)

Tested and works on Linux, OS X and Windows.
On OS X install latest Python 3.6 and run https://github.com/Contraz/pyrocket/blob/master/example.py

Also, thanks a lot of making this editor as I am also primary on OS X these days. I made a simple editor with ncurses, but that doesn't really cut it in the long run. I thought about making and editor using the built in tk-support in python (Clunky, but a lot more powerful than people might think)

**Comment by emoon** [comment]
Cool! :) I'm going to spend a bunch of weeks from now on doing some new work on the editor (the largest being this #133) so if you have any other suggestions I would love to hear that.

**Comment by einarf** [comment]
Other than not being able to toggle pause mode from the client (I don't think standard "rocket" supports it, but I haven't actually tested it with this editor), a curve editor would be a killer feature :)

**Comment by einarf** [comment]
Closing this one. Link to the client/player will be added in the rocket repo.
