### ISSUE TITLE
Pause state from the client

### ISSUE THREAD

**Issue by einarf** [emoon/rocket#135]
This have been mention in several other client projects and might be an issue with the "standard rocket protocol". It's not strictly needed, but definitely a nice to have.

Currently you cannot update the pause state from the client. Since we are sending the row to the editor.. pausing on he client is easy enough, but the bool state in the editor will be out of sync.

I tried sending a `PAUSE(4)` with `0/1` to this editor (without actually looking at the code) and it seems the command is processed, but ignored.

I'm not entirely sure how other editors will respond to `PAUSE(4)`, so this might not be worth risking if it breaks compatibility. Not too familiar with what is out here (yet).

**Comment by einarf** [comment]
The standard client only reads `GET_TRACK` and `SET_ROW`.
https://github.com/rocket/rocket/blob/master/editor/syncclient.cpp#L98-L112

Considering there are multiple editors out there I'm not sure if there's a graceful way to support this without breaking everything.

**Comment by emoon** [comment]
Yeah I think that protocol changes needs to go to the original rocket first. I don't want to add stuff to the protocol and diverge it unless it's really needed.

**Comment by emoon** [comment]
Closing this one for now. If it  gets added in the original rocket version I will consider supporting it
