### ISSUE TITLE
Setting rows per beat in the editor

### ISSUE THREAD

**Issue by bstrr** [emoon/rocket#45]
... allowing the user to control which n'th number of rows are highlighted as well as the jump-interval when using alt+arrowup/down.

**Comment by yupferris** [comment]
+1; in [backscatter](http://www.pouet.net/prod.php?which=65966) we ended up forking the official editor so that the highlighted rows were in multiples of 6 instead of 4, as the soundtrack was based on triplets.

**Comment by emoon** [comment]
Very doable as I have already prepared a bit for it (this as already data driven) low-fi version would be to just save it in the xml file (first time if the field isn't there) and that allows the user to tweek it. Would that be ok with you @yupferris ?

**Comment by yupferris** [comment]
yeah I think that'd be fine. It's something you basically change once _maybe_ twice per project, so even if I have to manually edit the xml I'd be pretty happy :) it's a big improvement over rebuilding the sync tracker to pull up other projects.. :D

**Comment by emoon** [comment]
yeah :)

**Comment by emoon** [comment]
Actually I will fix this as UI setting instead. Shouldn't be too bad.

**Comment by emoon** [comment]
This has been implemented now so closing this one.
